[2024-11-01T17:14:53.575+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_queimadas.check_url scheduled__2024-10-31T13:35:00+00:00 [queued]>
[2024-11-01T17:14:53.581+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_queimadas.check_url scheduled__2024-10-31T13:35:00+00:00 [queued]>
[2024-11-01T17:14:53.582+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-01T17:14:53.591+0000] {taskinstance.py:2214} INFO - Executing <Task(BranchPythonOperator): check_url> on 2024-10-31 13:35:00+00:00
[2024-11-01T17:14:53.597+0000] {standard_task_runner.py:60} INFO - Started process 14922 to run task
[2024-11-01T17:14:53.599+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_queimadas', 'check_url', 'scheduled__2024-10-31T13:35:00+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/dag_cria_emr.py', '--cfg-path', '/tmp/tmpuxo1kxtt']
[2024-11-01T17:14:53.601+0000] {standard_task_runner.py:88} INFO - Job 272: Subtask check_url
[2024-11-01T17:14:53.663+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_queimadas.check_url scheduled__2024-10-31T13:35:00+00:00 [running]> on host 3f04bb9d0c09
[2024-11-01T17:14:53.751+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_queimadas' AIRFLOW_CTX_TASK_ID='check_url' AIRFLOW_CTX_EXECUTION_DATE='2024-10-31T13:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-31T13:35:00+00:00'
[2024-11-01T17:14:53.756+0000] {logging_mixin.py:188} INFO - Erro ao acessar o site: HTTPSConnectionPool(host='dataserver-coids.inpe.br', port=443): Max retries exceeded with url: /queimadas/queimadas/focos/csv/mensal/Brasil/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x71e618dd4ca0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-11-01T17:14:53.756+0000] {python.py:202} INFO - Done. Returned value was: site_off
[2024-11-01T17:14:53.757+0000] {branch.py:35} INFO - Branch into site_off
[2024-11-01T17:14:53.757+0000] {skipmixin.py:178} INFO - Following branch site_off
[2024-11-01T17:14:53.769+0000] {skipmixin.py:244} INFO - Skipping tasks [('site_on', -1)]
[2024-11-01T17:14:53.800+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_queimadas, task_id=check_url, execution_date=20241031T133500, start_date=20241101T171453, end_date=20241101T171453
[2024-11-01T17:14:53.851+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-01T17:14:53.887+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
