[2024-10-25T21:33:10.096+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_queimadas.send_tweet manual__2024-10-25T21:33:08.279124+00:00 [queued]>
[2024-10-25T21:33:10.105+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_queimadas.send_tweet manual__2024-10-25T21:33:08.279124+00:00 [queued]>
[2024-10-25T21:33:10.105+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-25T21:33:10.118+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): send_tweet> on 2024-10-25 21:33:08.279124+00:00
[2024-10-25T21:33:10.124+0000] {standard_task_runner.py:60} INFO - Started process 10023 to run task
[2024-10-25T21:33:10.126+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_queimadas', 'send_tweet', 'manual__2024-10-25T21:33:08.279124+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/dag_cria_emr.py', '--cfg-path', '/tmp/tmpeos53z8b']
[2024-10-25T21:33:10.128+0000] {standard_task_runner.py:88} INFO - Job 187: Subtask send_tweet
[2024-10-25T21:33:10.161+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_queimadas.send_tweet manual__2024-10-25T21:33:08.279124+00:00 [running]> on host 622b1ac036ca
[2024-10-25T21:33:10.231+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_queimadas' AIRFLOW_CTX_TASK_ID='send_tweet' AIRFLOW_CTX_EXECUTION_DATE='2024-10-25T21:33:08.279124+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-25T21:33:08.279124+00:00'
[2024-10-25T21:33:10.537+0000] {logging_mixin.py:188} INFO - Erro ao enviar tweet: 400 Client Error: Bad Request for url: https://api.twitter.com/1.1/statuses/update.json?status=Aqui+vai+o+seu+tweet%21
[2024-10-25T21:33:10.540+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-10-25T21:33:10.561+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_queimadas, task_id=send_tweet, execution_date=20241025T213308, start_date=20241025T213310, end_date=20241025T213310
[2024-10-25T21:33:10.619+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-25T21:33:10.631+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
