[2024-10-25T21:37:50.005+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_queimadas.send_tweet manual__2024-10-25T21:37:48.770041+00:00 [queued]>
[2024-10-25T21:37:50.014+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_queimadas.send_tweet manual__2024-10-25T21:37:48.770041+00:00 [queued]>
[2024-10-25T21:37:50.015+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-25T21:37:50.029+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): send_tweet> on 2024-10-25 21:37:48.770041+00:00
[2024-10-25T21:37:50.038+0000] {standard_task_runner.py:60} INFO - Started process 10135 to run task
[2024-10-25T21:37:50.040+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_queimadas', 'send_tweet', 'manual__2024-10-25T21:37:48.770041+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/dag_cria_emr.py', '--cfg-path', '/tmp/tmpgr8yjy9z']
[2024-10-25T21:37:50.043+0000] {standard_task_runner.py:88} INFO - Job 189: Subtask send_tweet
[2024-10-25T21:37:50.083+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_queimadas.send_tweet manual__2024-10-25T21:37:48.770041+00:00 [running]> on host 622b1ac036ca
[2024-10-25T21:37:50.146+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_queimadas' AIRFLOW_CTX_TASK_ID='send_tweet' AIRFLOW_CTX_EXECUTION_DATE='2024-10-25T21:37:48.770041+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-25T21:37:48.770041+00:00'
[2024-10-25T21:37:50.432+0000] {logging_mixin.py:188} INFO - HTTP error occurred: 403 Client Error: Forbidden for url: https://api.twitter.com/1.1/statuses/update.json?status=Aqui+vai+o+seu+tweet%21
[2024-10-25T21:37:50.433+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-10-25T21:37:50.440+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_queimadas, task_id=send_tweet, execution_date=20241025T213748, start_date=20241025T213750, end_date=20241025T213750
[2024-10-25T21:37:50.493+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-25T21:37:50.510+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
